[
  {
    "summary": "[자동화] Centurion 예약 정보 수정 확인 테스트",
    "description": "에러 메시지: tests\\test_cen_reservation_edit.py:70: AssertionError\n\n파일: tests/test_cen_reservation_edit.py\n테스트 이름: Centurion 예약 정보 수정 확인 테스트\n\n스택 요약:\n → ============================== 1 failed in 2.12s ==============================",
    "project": "CEN",
    "issuetype": "Bug",
    "priority": "Medium",
    "labels": [
      "auto-test",
      "fail"
    ],
    "file": "tests/test_cen_reservation_edit.py"
  },
  {
    "summary": "[자동화] Centurion 녹취 확인 테스트",
    "description": "에러 메시지: E   ModuleNotFoundError: No module named 'scripts.record_slack'\n\n파일: tests/test_cen_record.py\n테스트 이름: Centurion 녹취 확인 테스트\n\n스택 요약:\n → ============================== 1 error in 0.17s ===============================",
    "project": "CEN",
    "issuetype": "Bug",
    "priority": "Medium",
    "labels": [
      "auto-test",
      "fail"
    ],
    "file": "tests/test_cen_record.py"
  },
  {
    "summary": "[자동화] 다국어 확인 테스트",
    "description": "에러 메시지: FAILED tests/test_home_language.py::test_language_check_all - AssertionError:...\n\n파일: tests/test_home_language.py\n테스트 이름: 다국어 확인 테스트\n\n스택 요약:\n → ============================= 1 failed in 11.03s ==============================",
    "project": "HOME",
    "issuetype": "Bug",
    "priority": "Medium",
    "labels": [
      "auto-test",
      "fail"
    ],
    "file": "tests/test_home_language.py"
  },
  {
    "summary": "[자동화] Centurion 예약 확정/취소 확인 테스트",
    "description": "에러 메시지: ..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError\n\n파일: tests/test_cen_reservation_accept.py\n테스트 이름: Centurion 예약 확정/취소 확인 테스트\n\n스택 요약:\n → ======================== 1 failed in 89.73s (0:01:29) =========================",
    "project": "CEN",
    "issuetype": "Bug",
    "priority": "Medium",
    "labels": [
      "auto-test",
      "fail"
    ],
    "file": "tests/test_cen_reservation_accept.py"
  },
  {
    "summary": "[자동화] test_cen_event_register 테스트",
    "description": "에러 메시지: FAILED tests/test_cen_event_register.py::test_register_event - AssertionError...\n\n파일: tests/test_cen_event_register.py\n테스트 이름: test_cen_event_register 테스트\n\n스택 요약:\n → ======================== 1 failed in 69.37s (0:01:09) =========================",
    "project": "CEN",
    "issuetype": "Bug",
    "priority": "Medium",
    "labels": [
      "auto-test",
      "fail"
    ],
    "file": "tests/test_cen_event_register.py"
  }
]